### ISSUE TITLE
Pdf Version for Learn-Web-Hacking

### ISSUE THREAD

**Issue by ShadowDrifterII** [LyleMi/Learn-Web-Hacking#12]
Can you add the ability to download "Learn-Web-Hacking"  As **PDF** Like "Learn-Binary-Hacking" ?
I know you make a lot of updates but it would be nice to add this

**Comment by LyleMi** [comment]
Thanks for your suggestion, I added pdf support, now you can download it from [here](https://websec.readthedocs.io/_/downloads/zh/latest/pdf/).
