### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by gh0stkey** [LyleMi/Learn-Web-Hacking#7]
地址：https://github.com/LyleMi/Learn-Web-Hacking/blob/master/source/vuln/xss/sop.rst

原文：
```
对于这种情况，可以在两个方面各自设置 document.damain='a.com' 来改变其源来实现以上任意两个页面之间的通信。
```

`document.damain='a.com'  -> document.domain='a.com'`

**Comment by LyleMi** [comment]
已修改，非常感谢 😃
