### ISSUE TITLE
创建隐藏用户后门内容出现错误

### ISSUE THREAD

**Issue by FanqXu** [LyleMi/Learn-Web-Hacking#8]
## [第6章内网渗透之持久化-Windows创建隐藏用户后门](https://websec.readthedocs.io/zh/latest/intranet/winpersistence.html#id9)：

> Windows可以使用在用户名后加入 $ 来创建匿名用户，这种方式创建的用户只能通过注册表查看。

通过在用户名后加 $ 创建的隐藏用户，在控制面板就可以看见；
而只能通过注册表查看的用户应该是「影子帐户」。

**Comment by LyleMi** [comment]
已经修改描述，感谢师傅指出~
